#pragma once
enum e_ErrorState
{
	NO_ERR,
	MF_STARTUP_ERR,
	MF_CREATE_ATTRIBUTES_ERR,
	MF_SET_GUID_ERR,
	MF_ENUM_DEVICE_SOURCES_ERR,
	MF_NO_VIDEO_DEVICE_ERR,
	MF_ACTIVATE_DEVICE_ERR,
	MF_SOURCE_READER_ERR,
	MF_SAMPLE_READ_ERR,
	MF_READER_PTR_ERR,
};