#pragma once
#ifdef __cplusplus
extern "C" {
#endif

	enum struct errorState : int32_t
	{
		ERR = INT_MIN,
		NOT_IMPLEMENTED_YET_ERR,
		UNDEFINED_DEVICE_TYPE_ID_ERR,
		CREATE_DEVICE_MONITOR_ERR,
		START_DEVICE_MONITOR_ERR,
		NO_VIDEO_DEVICE_FOUND_ERR,
		GET_DEVICE_INFO_READABLE_ERR,
		NULLPTR_ERR,
		SET_SOURCE_ELEMENT_ERR,
		SET_SINK_ELEMENT_ERR,
		SET_SOURCE_CAPS_ERR,
		SET_SINK_CAPS_ERR,
		EMPTY_STRING_ERR,
		CONVERSION_ERR,
		OBJECT_CREATION_ERR,
		BUILD_PIPELINE_FAILED,
		START_STREAMING_FAILED,
		STOP_STREAMING_FAILED,
		NO_ERR
	};
#ifdef __cplusplus
}
#endif