#pragma once
enum errorState
{
	ERR = -(1 << 7),
	NOT_IMPLEMENTED_YET_ERR,
	UNDEFINED_DEVICE_TYPE_ID_ERR,
	CREATE_DEVICE_MONITOR_ERR,
	START_DEVICE_MONITOR_ERR,
	NO_VIDEO_DEVICE_FOUND_ERR,
	GET_DEVICE_INFO_READABLE_ERR,
	NULLPTR_ERR,
	SET_SOURCE_ELEMENT_ERR,

	NO_ERR = 0
};